// <auto-generated />
namespace Cashed.DataAccess.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Expsense_Upgrade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Expsense_Upgrade));
        
        string IMigrationMetadata.Id
        {
            get { return "201710091754197_Expsense_Upgrade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
