// <auto-generated />
namespace Cashed.DataAccess.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsDeletedField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsDeletedField));
        
        string IMigrationMetadata.Id
        {
            get { return "201710141256101_IsDeletedField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
